apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-volume-claim
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
      - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi 
