apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        env: stage
        type: front-end
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3
  selector:
    env: stage
