---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-blue-v4
  labels:
    app: nginx
    type: front-end
    version: v4
    color: blue
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        type: front-end
        version: v4
        color: blue
    spec:
      containers:
        - name: nginx
          image: sunlnx/kubenginx:v4
  replicas: 4
  selector:
    matchLabels:
      type: front-end
