---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
  labels:
    image: ubuntu
    app: sleeper
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["sh"]
      args: ["-c", "while true; do echo Hello world; sleep 10; done"]
