---
apiVersion: v1
kind: Pod
metadata:
  name: initcontainers
spec:
  containers:
    - name: main
      image: busybox
      command: ["sh","-c","while true; do echo 'main program' && sleep 2; done"]
  initContainers:
    - name: init-1
      image: busybox
      command: ["echo","I am init container for sleep"]
    - name: init-2
      image: busybox
      command: ["sleep","30"]
