---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp001
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mywebapp001
  template:
    metadata:
      labels:
        app: mywebapp001
    spec:
      containers:
      - name: mywebapp001
        image: sunlnx/mywebapp:0.0.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mywebapp001
spec:
  selector:
    app: mywebapp001
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
