apiVersion: v1
kind: Pod
metadata:
  name: secretpods
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: DB_PASSWORD
          valueFrom:
              secretKeyRef:
                name: dbsecret
                key: dbpassword
