apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-restapi-deployment
  labels:
    app: spring-restapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-restapi
  template:
    metadata:
      labels:
        app: spring-restapi
    spec:
      containers:
      - name: spring-restapi
        image: sunlnx/spring-rest-example
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-restapi-service
spec:
  selector:
    app: spring-restapi
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31081
