# michelle's responsibilities are growing and now she will be responsible for storage as well. Create the required ClusterRoles and ClusterRoleBindings to allow her access to Storage.

# Get the API groups and resource names from command kubectl api-resources. Use the given spec.

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name:  storage-admin
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["storageclasses"]
  verbs: ["get", "list", "delete", "create"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "delete", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: michelle-storage-admin
subjects:
- kind: User
  name:  michelle
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: storage-admin
  apiGroup: rbac.authorization.k8s.io
