kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-vol1
spec:
  accessModes: [ "ReadWriteOnce" ]
  capacity:
   storage: 1Gi
  persistentVolumeReclaimPolicy: Delete
  hostPath:
   path: /tmp/data
