apiVersion: v1
kind: Pod
metadata:
  name: nginxhttpliveness
  labels:
    app: nginx
spec:
  containers:
    - name: nginxstartup
      image: nginx
      livenessProbe:
        httpGet:
          path: /index.html
          port: 80
        failureThreshold: 1
        periodSeconds: 10
      #  the application will have a maximum of 5 minutes (30 * 10 = 300s) to finish its startup.
      startupProbe:
        httpGet:
          path: /index.html
          port: 80
        failureThreshold: 30
        periodSeconds: 10
