apiVersion: v1
kind: Pod
metadata:
  name: liveness
  labels:
    app: nginx
    test: liveness
    env: test-liveness
spec:
  containers:
    - name: nginx
      image: nginx
      livenessProbe:
        exec:
          command:
            - cat
            - /usr/share/nginx/html/index.html
        initialDelaySeconds: 5
        periodSeconds: 5
