---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-pod-svc
spec:
  selector:
    name:  nginx
  type:  NodePort
  ports:
  - name:  nginx
    port:  80
    targetPort:  80
    nodePort: 30012
